### ISSUE TITLE
P2P protocol for the dev node?

### ISSUE THREAD

**Issue by HarukaMa** [d0cd/slingshot#7]
This is actually more like a personal feature request as it's could be really useless for a local node, but it could be very useful for me to develop the explorer as I need some example data for deployment transactions, and the explorer couldn't parse the data from REST server (mainly because I don't have a parser for Aleo instructions so I can't serialize the data).

**Comment by d0cd** [comment]
Could you elaborate a bit more on how you would like the architecture to look like?
Would you like to be able to spin up multiple dev nodes that can talk to one another?

**Comment by d0cd** [comment]
Archiving.
