### ISSUE TITLE
[Bug] Execution of transition with opcodes other than increment or decrement in finalize fails silently and builds/deploys without errors.

### ISSUE THREAD

**Issue by arosboro** [d0cd/slingshot#8]
## 🐛 Bug Report

When I get unspent records after calling execute, they are unsuable.

## Steps to Reproduce

1. start slingshot node
2. pour to program.json dev address
3. deploy program.json
4. pour credits to the account public key performing execute, otherwise unspent records not generated
5. execute program transition
6. fetch unspent records with rest api

```
async function execute() {
  const account: Account = network.acc00.account;
  const arg0 = random_seed.value?.toString() + "u64";
  const arg1 = player01.value?.toString();
  const arg2 = player02.value?.toString();
  const arg3 = player03.value?.toString();
  const arg4 = player04.value?.toString();
  const arg5 = player05.value?.toString();
  const arg6 = player06.value?.toString();
  const arg7 = player07.value?.toString();
  const transaction = {
    private_key: account.privateKey().to_string(),
    program_id: "aleo_casino_table.aleo",
    function_name: "main",
    inputs: [arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7],
  };
  try {
    const result = await axios.post(
      "/api/testnet3/program/execute",
      transaction
    );
    console.log(result.data.transaction_id);
    // Then get the transaction and store the relevant results
    // TODO: This fails
    // const transaction_id = result.data.transaction_id;
    // const uri = "/api/testnet3/transaction/" + transaction_id;
    // try {
    //   const tx_result = await axios.get(uri);
    //   console.log(tx_result);
    // } catch (e) {
    //   console.log(e);
    // }
    // It should show up in unspent records as soon as program/execute resolves
    try {
      const unspent_records = await axios.post(
        "/api/testnet3/records/unspent",
        {
          view_key: account.viewKey().to_string(),
        }
      );
      console.log(unspent_records.data.records);
      aleo_casino_table.records.push(...unspent_records.data.records);
    } catch (e) {
      console.log(e);
    }
  } catch (e) {
    console.log(e);
  }
}
```

#### Stack trace & error message

```
{"records":{"6128002122280393105419329789758061510301253457256368507560570563845172070320field":"{\n  owner: aleo1jtyt4rr8ruuw7m0c2fa2aw7u3mfwh9wv93pwqzeg833uzruz9sys70w7r7.private,\n  gates: 100u64.private,\n  _nonce: 2066018283382385095457425506544294315781969064414559263701607257668311319163group.public\n}"}}
```

## Expected Behavior

Expected a json object representing all record properties.  As it stands the information provided by the input is neither consumable json nor reveals anything of value to the application state.

## Your Environment

all latest dependencies built daily

**Comment by arosboro** [comment]
it seems JSON.parse on the string value could get the object, but it shouldn't require parsing to get a record object, it should already be serialized into a javascript object.

**Comment by arosboro** [comment]
@d0cd I think the issue here is that I'm seeing an unspent record from a previous pour from the faucet and no record generated by the execute rest api.  The execute command appears in the ledger history, however.  

It makes sense that for Object.keys(response.data.records) you would iterate each field key and JSON.parse the string value set for that record.  JSON is more a universal message body than native JavaScript if the goal is for flexibility of different languages such as python, rust or others for example.

In my case the confusion came from utilizing a full stack javascript framework and not anticipating having to do anything special with response records to parse them successfully.  Further confusion was arrived at when the record was not matching the definition of the contract I executed.

**Comment by arosboro** [comment]
@d0cd for historical purposes mentioning your response from discord: You said it is because opcodes increment and decrement are the only opcodes permitted in finalize.

**Comment by d0cd** [comment]
Archiving.
