### ISSUE TITLE
[Bug]Cannot deploy contracts with imports.

### ISSUE THREAD

**Issue by QiuPengwu** [d0cd/slingshot#9]
## Steps to Reproduce

1. write a contract with a directory of imports
2. start the local node and receive test tokens at the tap 
3. execute the deploy contract command

## code info

![image](https://user-images.githubusercontent.com/19848798/212297602-bbf3bd4b-0577-4ff9-bf90-0f96baf4618f.png)

![image](https://user-images.githubusercontent.com/19848798/212297681-6d72aa7a-0b7d-442a-913c-8e19b36eb48a.png)
 
## error info

![image](https://user-images.githubusercontent.com/19848798/212295263-f9354cc0-5793-43bd-8655-be8f65faa9c8.png)
![image](https://user-images.githubusercontent.com/19848798/212295388-0ba35fef-63ff-4e50-978b-71ca4b64c240.png)

**Comment by d0cd** [comment]
Thanks for filing the issue!
We have a fix in #10. It will require you to deploy the imported program before the main program.
For example, 
```
slingshot deploy compare.aleo -f 10000000
slingshot deploy three_card_poker.aleo -f 1000000
```
Note that the fees may not be sufficient.

**Comment by QiuPengwu** [comment]
Okay, I'll test if it works.

**Comment by QiuPengwu** [comment]
After switching branches you can deploy it, it just needs too many fee's.

![image](https://user-images.githubusercontent.com/19848798/212591417-e23f576e-d3e3-4c08-81e0-dc4ed6309589.png)

**Comment by d0cd** [comment]
Fees are proportional to the size of your program.
Furthermore, the fee amount is in "gates" which is sub-denomination of "credits"
